### ISSUE TITLE
Submit button for stops report

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [pouyalireza/TNAST_MAVEN#32]
I tried to run the stops report for Baker County (County Report->Rural Stops), and shows the people mover routes with no visits, using the May 2017 database. I checked the GTFS, and these stops have entries in stop_times.txt, but this route only runs the 2nd and 4th Thursday of the month. I tried to use the date selector to try to select 8/24/17 to check the report behavior on a date that has stops, and clicking the submit button doesn't appear to do anything. I can't be sure if the report refreshed, and there's something wrong with the calendar, or if the report submit button is broken.

**Comment by pouyalireza** [comment]
@PPaulsonOregonDOT  This error has been fixed in commit  2ab8458097531ed835e6e0cb2e6e083b35448e31

**Comment by PPaulsonOregonDOT** [comment]
@pouyalireza This issue remains in the tool. When you hit the submit button after selecting a date in the date selector, the report refreshes with current day selected, which has results in reports not changing based on date selection.

**Comment by ed-g** [comment]
Phillip

> The trillium software version appears to still be broken.

Srinivas

> I fixed this, but new code may have broken it again.

**Comment by ed-g** [comment]
What's the full URL to to "Baker County (County Report->Rural Stops)"?

I started here via "(toolbar icon of paper page)" -> "Counties Reports" 

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/GeoCountiesReport.html?&dbindex=9&popYear=2010

Then clicked link GEOID "41001" on the leftmost column and got to here:

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/GeoCountiesXreport.html?&areaid=41001&x=0.25&l=2&n=inr&dbindex=9&popYear=2010&nav=stateS-countyS

Then clicked button labeled "1 day(s) selected" which opened a calendar view.

Then "submit" to the right of the calendar which caused a page referesh, and "1 day(s)" is now selected.

**Comment by ed-g** [comment]
addDate('2017-08-22') in js console adds to selection list.

**Comment by ed-g** [comment]
`$('#datepicker').multiDatesPicker({ 'addDates': [ new Date('2017-09-20') ] })` will add a date to the date picker, but does not add to list of dates to left of calendar.

**Comment by srinivas13794** [comment]
http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?&areaid=41001&type=0&x=0.25&n=ior&dbindex=9&popYear=2010&geotype=-1&geoid=null&rc=1&stime=0:00&etime=23:59&nav=stateS-countyS

Here is the URL for baker county rural stops

**Comment by ed-g** [comment]
Ok great thanks!

**Comment by srinivas13794** [comment]
I have been looking at this bug there seems to be a problem with the query
that runs this report.Does not increase the number of trips when more than
a day is selected

**Comment by ed-g** [comment]
Here is a test URL with multiple dates selected.

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?&areaid=41001&type=0&x=0.25&n=ilrimrior&dbindex=9&popYear=2010&geotype=-1&geoid=null&rc=1&stime=0:00&etime=23:59&nav=stateS-countyS

**Comment by ed-g** [comment]
Side note, an issue with the page I referenced earlier http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/GeoCountiesXreport.html does not seem to modify the n=.... parameter from javascript before re-submitting the form.

**Comment by ed-g** [comment]
@srinivas13794 how about as a next step, let's see if we can test the query with multiple days, in isolation.

**Comment by ed-g** [comment]
@srinivas13794 @BenFields724 does that sound like a good next step to you? If not what would you suggest?

**Comment by srinivas13794** [comment]
@ed-g I tested the query out for a day and compared it against multiple days and I could see that the number of trips remained the same.I am trying to find ways to fix this.

**Comment by ed-g** [comment]
Can you paste the sql query text as a comment to this issue?

**Comment by ed-g** [comment]
Rather, paste it here if you would like my help with debugging.

If you have it in hand and don't need my help then there's no need to paste code, or show me how things work.

**Comment by PPaulsonOregonDOT** [comment]
I had a chance to dig into this bug a little bit further, and it appears that the datepicker is defaulting to the current day for all changes to the calendar selection. For instance, I have chosen a different day and an entire week of dates in the datepicker, and the report reverts to the current day. Let me know if there is more testing I can do to help zero in on a solution.

**Comment by ed-g** [comment]
@srinivas13794 @BenFields724 any updates on this? Do you need my help?

**Comment by srinivas13794** [comment]
I have fixed this I will upload this onto the trillium server and let you
know

**Comment by srinivas13794** [comment]
@PPaulsonOregonDOT @ed-g @ODOT-RPTD-mb  This issue has been fixed on trillium's [development verison](http://tna.trilliumtransit.com:8080/?&n=--&dbindex=10) of the tool.
